[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
tauri = { version = "2", features = ["unstable"] }
tauri-plugin-shell = "2"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
notify = { version = "7", features = ["macos_kqueue"] }
notify-debouncer-mini = "0.5"
portable-pty = "0.9.0"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[lib]
name = "hello_world_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
panic = "abort"
